name: Go

on:
  schedule:
    - cron: "0 15 * * *"
  workflow_dispatch: {}

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...
      
    - name: Run
      env:
        GUILD_ID: ${{ secrets.GUILD_ID }}
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
      run: ./whatbot -g $GUILD_ID -t $DISCORD_TOKEN -i icons
